config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  # these routes are for showing users a login form, logging them in, and logging them out.
  resources :sessions do 
    collection do
      get '/login' => 'sessions#new'
      post '/login' => 'sessions#create'
      delete :logout
    end
  end

  resources :products do
    collection do
      get :add_variant
    end
  end

  resources :orders do
    collection do
      get :add_product
      get :add_variant
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :set_locale
  before_action :valid_session
  before_action :get_path

  def set_locale
    I18n.locale = params[:locale] ||= 'en'
  end

  def valid_session
    @current_user = Redis.current.get("login-#{cookies[:token]}")
    @current_user = JSON.parse(@current_user)  if @current_user
    valid_token
    return redirect_to login_sessions_path() if !@current_user
  end

  def languajes
    @languaje = [["Eng","en"],["Esp","es"]]
  end

  def get_path
    uri = URI(request.url)
    @path = uri.path
  end

  private 
    def valid_token
      flag = false
      if !@current_user.nil?
        response = ApiVivetech::validate_token(@current_user['token'])
        if response['errors']
          Redis.current.del("login-#{@token_session}")
          redirect_to login_sessions_path()
        end
      end
      return flag
    end
    

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @title = t('common_texts.home')
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def new
    @title = t('orders.new')
    @order = {}
  end

  def add_variant
    @variant_index = params[:product_index]
    @variant = {name: '', price: ''}
  end

  def add_product
    @product = {name: '', desciption: ''}
  end
  
  def index
    @title = t('orders.list')
    response = ApiVivetech::get_orders(@current_user['token'])
    @orders = response['data']
  end
    
  def show
    @title = t('orders.show')
    response = ApiVivetech::get_order({id: params[:id], token: @current_user['token']})
    if !response['status']
      flash[:alert] = t('orders.search')
      redirect_to controller: 'orders', action: "index"
    end
    @order = response['data']
  end
  
  def create
    response = ApiVivetech::create_order({data: params[:data], token: @current_user['token']})
    if response['status']
      flash[:alert] = t('orders.save.success')
      redirect_to controller: 'orders', action: "index"
    else
      flash[:warning] = t('orders.save.error')
      redirect_to controller: 'orders', action: "new"
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def new
    @title = t('products.new')
    @product = {}
  end

  def add_variant
    @variant = {name: '', price: ''}
  end

  def index
    @title = t('products.list')
    response = ApiVivetech::get_products(@current_user['token'])
    @products = response['data']
  end
    
  def show
    @title = t('products.show')
    response = ApiVivetech::get_product({id: params[:id], token: @current_user['token']})
    if !response['status']
      flash[:alert] = t('products.search')
      redirect_to controller: 'products', action: "index"
    end
    @product = response['data']
  end

  def create
    params[:product][:variants] = params[:variants]
    response = ApiVivetech::create_product({data: params[:product], token: @current_user['token']})
    if response['status']
      flash[:alert] = t('products.save.success')
      redirect_to controller: 'products', action: "index"
    else
      flash[:warning] = t('products.save.error')
      redirect_to controller: 'products', action: "new"
    end
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :languajes
  skip_before_action :valid_session, except: [:logout]

  def new
      
  end

  def create
    response = ApiVivetech::login(params[:sessions])
    if response['status']
      cookies[:token] = response['data']['token']
      Redis.current.set("login-#{response['data']['token']}",response['data'].to_json)
      redirect_to controller: 'home', action: "index"
    else
      flash[:warning] = response['message']
      redirect_to controller: 'sessions', action: "new"
    end
  end

  def logout
    Redis.current.del("login-#{cookies[:token]}")
    cookies[:token] = nil
    redirect_to controller: 'sessions', action: "new"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper

    def getStatus(status)

        case status.to_i
        when 0
            return 'Inactivo'
        when 1
            return 'Activo'
        end
        
    end

    def getSelled?(status)

        case status
        when true
            return 'Vendido'
        when false
            return 'En Stock'
        end
        
    end
    
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_sidebar.html.haml
%nav#sidebar
  %div.sidebar-header{align: "center"}
    %div{style: 'background: linear-gradient(to bottom,#BCDB00,#A0BA00,#839800,#5E6E00);'}
      %div.logo
        = image_tag 'sidebar/missing.png'
        %h5= @current_user['username']
        %h2 
          ID:
          = @current_user['id']

    %div.col-12.logomenu.nopadding
      %div.container
        %ul.list-unstyled.components{style: "margin-top:20px"}

          %li.only{style: "margin-top:10px;"}
            %a#Home.link-home{href: "/"}
              = image_tag 'sidebar/home.svg', class: 'sidebar-button-img' 
              %strong= t('sidebar.menu_1.title')

            %li{style: "margin-top:10px;"}
              %a.dropdown-toggle.sidebar-button.link-home{href: "#Product", 'data-toggle': "collapse", 'aria-expanded': "false"}
                = image_tag 'sidebar/product.png', class: 'sidebar-button-img'
                %strong= t('sidebar.menu_2.title')
                  
              %ul#Product.collapse.list-unstyled
                %li
                  %a#register.sidebar-button.link-home{href: "/products/new"}
                    = image_tag 'sidebar/dot-gray.png', class: 'sidebar-button-bullet'
                    %strong= t('sidebar.menu_2.submenu_1')      
                %li
                  %a#list.sidebar-button.link-home{href: "/products"}
                    = image_tag 'sidebar/dot-gray.png', class: 'sidebar-button-bullet'
                    %strong= t('sidebar.menu_2.submenu_2')

            %li{style: "margin-top:10px;"}
              %a.dropdown-toggle.sidebar-button.link-home{href: "#Order", 'data-toggle': "collapse", 'aria-expanded': "false"}
                = image_tag 'sidebar/product.png', class: 'sidebar-button-img'
                %strong= t('sidebar.menu_3.title')
                  
              %ul#Order.collapse.list-unstyled
                %li
                  %a#register.sidebar-button.link-home{href: "/orders/new"}
                    = image_tag 'sidebar/dot-gray.png', class: 'sidebar-button-bullet'
                    %strong= t('sidebar.menu_3.submenu_1')      
                %li
                  %a#list.sidebar-button.link-home{href: "/orders"}
                    = image_tag 'sidebar/dot-gray.png', class: 'sidebar-button-bullet'
                    %strong= t('sidebar.menu_3.submenu_2')


          %li.only{style: "margin-top:400px;"}
  
          %li{style: "margin-top:10px"}
            = link_to logout_sessions_path, method: :delete, class: 'sidebar-button font-white', id: 'logout-button' do
              = image_tag 'sidebar/logout.png', class: 'sidebar-button-img'
              = t('sidebar.logout')

app/views/layouts/_topbar.html.haml
%div.nav
  %div.information
    %h1= @title
    %h2= @path

app/views/layouts/application.html.haml
%html
  %head
    %title DashboardVivetech
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' 
    %link{href: "https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css", rel: "stylesheet"}
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  
- if @current_user 
  %body
    %div.main-container.mx-auto
      %div.main-grid
        %nav.container-nav
          = render partial: 'layouts/sidebar'
        %div{style: 'background: linear-gradient(to bottom,#5E6E00,#839800,#A0BA00,#BCDB00);margin-top: 15px'}
          = render partial: 'layouts/topbar'
          %div#notifications.mt-4
            = render partial: 'notifications/flash'
          = yield
    = render partial: '/modals/error'
    = render partial: '/modals/success'
- else
  %body.body_login
    %div.container
      %div.authentication
        %div#notifications.mt-4
          = render partial: 'notifications/flash'
        = yield

app/views/modals/_access.html.haml
%div.modal.fade#modalAccess{role:"dialog", "aria-labelledby": "exampleModalCenterTitle", "aria-hidden": "true"}
  %div.modal-dialog.modal-dialog-centered{role: "document"}
    %div.modal-content
      %div.customize-modal
        %div.modal-header
          %button.close{type: "button", "data-dismiss": "modal", "aria-label": "Close"}
            %span{'aria-hidden': "true"} &times;

        %div.modal-body
          %h1#body-tittle.body-tittle= t('modals.access')
          %h1.body-subtitle= t('modals.access.date')
          %h1#date-access.body 2021/04/11
          %h1.body-subtitle= t('modals.access.hour')
          %h1#hour-access.body 15:42
          %h1.body-subtitle= t('modals.access.user')
          %h1#user-access.body 0.00123BTC = 58.84 USD
          %h1.body-subtitle= t('modals.access.client')
          %h1#client-access.body Miguel.J@gmail.com

        %div.modal-footer
          %a{href: "/clients/access"}
            = t('modals.access.new_access')

app/views/modals/_confirm_sale.html.haml
#modalConfirmSale.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", role: "dialog", tabindex: "-1"}

  %div.modal-dialog.modal-dialog-centered{role: "document"}
    %div.modal-content
      %div.customize-modal
        %div.modal-header
          %button.close{type: "button", 'data-dismiss' => "modal", 'aria-label' => "Close"}
            %span{'aria-hidden': "true"} &times;
        %div.modal-body
          %h1#body-tittle.body-tittle= t('modals.sale')
          %h1.body= t('sales.amount_total')
          %h1.body-subtitle{id: "amount_total"}
          %h1.body= t('common_texts.total_items')
          %h1.body-subtitle{id: "total_products"}
          %h1.body= t('common_texts.member')
          %h1.body-subtitle{id: "member_id_modal"}

        %div.modal-footer
          %button.btn.btn-login{id: 'send_sale_modal'}
            = t('buttons.save')

app/views/modals/_error.html.haml
%div#modalError.modal.fade{role: "dialog", 'aria-labelledby': "exampleModalCenterTitle", 'aria-hidden': "true"}
  %div.modal-dialog.modal-dialog-centered{role: "document"}
    %div.modal-content
      %div.customize-modal
        %div.modal-header
          %button.close{type: "button", 'data-dismiss': "modal", 'aria-label': "Close"}
            %span{'aria-hidden': "true"} &times;

        %div.modal-body
          %h1#body-tittle.body-tittle= t('modals.error')
          %h1#message.body

app/views/modals/_success.html.haml
%div.modal.fade#modalSuccess{role: "dialog", 'aria-labelledby': "exampleModalCenterTitle", 'aria-hidden': "true"}>
  %div.modal-dialog.modal-dialog-centered{role: "document"}
    %div.modal-content
      %div.customize-modal
        %div.modal-header
          %button.close{type: "button", 'data-dismiss': "modal", 'aria-label': "Close"}
            %span{'aria-hidden': "true"} &times;
                        
        %div.modal-body
          %h1#body-tittle.body-tittle= t('modals.success')
          %h1#message.body-subtitle

app/views/notifications/_flash.html.haml
- if flash[:alert]
  %div.alert.alert-success.alert-position
    %strong
      = flash[:alert].delete('.')
      !
    %a.close{href: "#", 'data-dismiss': "alert", 'aria-label': "close"} &times;

- if flash[:danger]
  %div.alert.alert-danger.alert-position
    %strong
      = flash[:danger].delete('.')
      !
    %a.close{href: "#", 'data-dismiss': "alert", 'aria-label': "close"} &times;

- if flash[:notice]
  %div.alert.alert-success.alert-position
    %strong
      = flash[:notice].delete('.')
      !
    %a.close{href: "#", 'data-dismiss': "alert", 'aria-label': "close"} &times;

- if flash[:successfully]
  %div.alert.alert-success.alert-position
    %strong
      = flash[:successfully].delete('.')
      !
    %a.close{href: "#", 'data-dismiss': "alert", 'aria-label': "close"} &times;

- if flash[:warning]
  %div.alert.alert-warning.alert-position
    %strong
      = flash[:warning].delete('.')
      !
    %a.close{href: "#", 'data-dismiss': "alert", 'aria-label': "close"} &times;

app/views/orders/_add_product.html.haml
-id = SecureRandom.uuid.to_s[0,8]
=render partial: 'product', locals: {child_index: id, product: @product}

app/views/orders/_add_variant.html.haml
-id = SecureRandom.uuid.to_s[0,8]
=render partial: 'variant', locals: {child_index: id, variant: @variant}

app/views/orders/_form_fields.html.haml
%div.col-12.pt-4
  %h3 Products
  #products

%div.col-12.pt-5
  %a#bproduct.btn.btn-primary{style: 'color: white;padding: 1px;'} Add Product

%div.links.col-6.pt-4
  %a.btn.btn-link{href: "/products"}= t('buttons.back')

%div.button.col-6.pt-4
  %button.btn.btn-login= t('buttons.save')

:javascript

  $('#bproduct').on('click', function(){
    var url = "#{add_product_orders_url}";
    $.get( url ); 
  })

app/views/orders/_order.html.haml
%tr
  %td= order['id']
  %td= t("status.#{order['status']}")
  %td= order['correct']
  %td= order['incorrect']
  %td= order['total']
  %td
    %a.link-table{href: "/orders/#{order['id']}"}=t('buttons.show') 

app/views/orders/_orders.html.haml
%table.table.responsive.text-center{id: 'table_desing'}
  %thead
    %th=t('common_texts.id')
    %th=t('common_texts.status')
    %th=t('common_texts.correct')
    %th=t('common_texts.incorrect')
    %th=t('common_texts.total')
    %th=t('buttons.show')
  %tbody
    - if @orders.any?
      = render partial: 'orders/order', collection: @orders

app/views/orders/_product.html.haml
.del_product{id: "product_#{child_index}"}  
  .m-1.p-1.border.rounded.box
    %div.row
      %div.form-group.col-4
        %strong#error-name.error-msg
          = text_field_tag 'data[][name]',nil, {class: 'form-input', required: true,id:"name"}
          %label.form-label{for: "name"}= t('common_texts.name')
          %p#text-name.hide= t('errors.name')
    
      %div.form-group.col-4
        %strong#error-description.error-msg
          = text_field_tag 'data[][description]',nil, {class: 'form-input', required: true,id:"description"}
          %label.form-label{for: "description"}= t('common_texts.description')
          %p#text-description.hide= t('errors.description')

      %b
        %a.delete_product{data: {div_id: "product_#{child_index}"}}
          =image_tag('icons/delete.png')

      %div.col-12.pt-4{style: 'margin-left: 20px'}
        %h3 Variants
        #div{id: "variant_#{child_index}"}

        %div.col-12.pt-5
          %a.btn.btn-primary{style: 'color: white;padding: 1px;',id: "bvariant_#{child_index}"} Add Variant

:javascript

  $('.delete_product').on('click', function(){
    var div_id = $(this).data('div-id');
    $("#" + div_id).remove();
  });

  $("#bvariant_#{child_index}").on('click', function(){
    var url = "#{add_variant_orders_url}"; 
    $.get( url+"?product_index=#{child_index}" );
  })

app/views/orders/_variant.html.haml
.del_variant{id: "variant_#{child_index}"}  
  .m-1.p-1.border.rounded.box
    %div.row
      %div.form-group.col-4
        %strong#error-name.error-msg
          = text_field_tag 'data[][variants][][name]',nil, {class: 'form-input', required: true,id:"name"}
          %label.form-label{for: "name"}= t('common_texts.name')
          %p#text-name.hide= t('errors.name')
    
      %div.form-group.col-4
        %strong#error-price.error-msg
          = number_field_tag 'data[][variants][][price]',nil, {class: 'form-input', required: true,id:"price", step: 0.0001}
          %label.form-label{for: "price"}= t('common_texts.price')
          %p#text-price.hide= t('errors.price')

      %b
        %a.delete_variant{data: {div_id: "variant_#{child_index}"}}
          =image_tag('icons/delete.png')

:javascript

  $('.delete_variant').on('click', function(){
    console.log('entreo')
    var div_id = $(this).data('div-id');
    $("#" + div_id).remove();
  });

app/views/orders/add_product.js.erb
$('#products').prepend("<%= j(render partial: 'add_product')%>");

app/views/orders/add_variant.js.erb
$("#div_variant_<%= @variant_index %>").prepend("<%= j(render partial: 'add_variant')%>");

app/views/orders/index.html.haml
%div.container
  %div.row
    %div.card
      = render partial: 'orders'

app/views/orders/new.html.haml
%div.row
  %div.card
    = form_for :product, :url => { :action => "create"}, method: 'POST', :html => {:class => "form row"} do |f|
      = render partial: 'form_fields', locals: {f: f}

app/views/orders/show.html.haml
%div.container
  %div.row
    %div.card
      %div.row
        %div.col-4.p-2
          %h5= t('common_texts.order#')
          %h5 :
          %h5= @order['id']

        %div.col-4.p-2
          %h5= t('common_texts.correct')
          %h5 :
          %h5= @order['correct']
         
        %div.col-4.p-2
          %h5= t('common_texts.incorrect')
          %h5 :
          %h5= @order['incorrect']
        
        %div.col-4.p-2
          %h5= t('common_texts.total')
          %h5 :
          %h5= @order['total']
        
        %div.col-4.p-2
          %h5= t('common_texts.date_create')
          %h5 :
          %h5= DateTime.parse(@order['created_at']).strftime('%Y-%m-%d %H:%M')

        %div.col-12.p-2
          %div
            %h2= t('common_texts.products')
          %div.col-12
            - @order['products'].each do |product|
              %div.variants
                %div.col-4.p-2
                  %h5= t('common_texts.name')
                  %h5 :
                  %h5= product['name']
    
                %div.col-4.p-2
                  %h5= t('common_texts.description')
                  %h5 :
                  %h5= product['description']

                %div.col-4.p-2
                  %a.link-table{href: "/products/#{product['id']}"}=t('buttons.show')
        
        %div.links.col-10.pt-4
          %a.btn.btn-link{href: "/products"}= t('sales.inputs.back')

app/views/products/_form_fields.html.haml
%div.form-group.col-4
  %strong#error-name.error-msg
    = f.text_field :name, class: 'form-input', required: true,id:"name", value: @product['name']
    %label.form-label{for: "name"}= t('common_texts.name')
    %p#text-name.hide= t('errors.name')

%div.form-group.col-4
  %strong#error-description.error-msg
    = f.text_field :description, class: 'form-input', required: true,id:"description", value: @product['description']
    %label.form-label{for: "description"}= t('common_texts.description')
    %p#text-description.hide= t('errors.description')

%div.col-12.pt-4
  %h3 Variants
  #variants

%div.col-12.pt-5
  %a#bvariant.btn.btn-primary{style: 'color: white;padding: 1px;'} Add Variant

%div.links.col-6.pt-4
  %a.btn.btn-link{href: "/products"}= t('buttons.back')

%div.button.col-6.pt-4
  %button.btn.btn-login= t('buttons.save')

:javascript

  $('#bvariant').on('click', function(){
    var url = "#{add_variant_products_url}";
    $.get( url ); 
  })

app/views/products/_product.html.haml
%tr
  %td= product['name']
  %td= product['description']
  %td
    %a.link-table{href: "/products/#{product['id']}"}=t('buttons.show') 

app/views/products/_products.html.haml
%table.table.responsive.text-center{id: 'table_desing'}
  %thead
    %th=t('common_texts.name')
    %th=t('common_texts.description')
    %th=t('buttons.show')
  %tbody
    - if @products.any?
      = render partial: 'products/product', collection: @products

app/views/products/_variant.html.haml
.del_variant{id: "variant_#{child_index}"}  
  .m-1.p-1.border.rounded.box
    %div.row
      %div.form-group.col-4
        %strong#error-name.error-msg
          = text_field_tag 'variants[][name]',nil, {class: 'form-input', required: true,id:"name"}
          %label.form-label{for: "name"}= t('common_texts.name')
          %p#text-name.hide= t('errors.name')
    
      %div.form-group.col-4
        %strong#error-price.error-msg
          = number_field_tag 'variants[][price]',nil, {class: 'form-input', required: true,id:"price", step: 0.0001}
          %label.form-label{for: "price"}= t('common_texts.price')
          %p#text-price.hide= t('errors.price')

      %b
        %a.delete_variant{data: {div_id: "variant_#{child_index}"}}
          =image_tag('icons/delete.png')

:javascript

  $('.delete_variant').on('click', function(){
    console.log('entreo')
    var div_id = $(this).data('div-id');
    $("#" + div_id).remove();
  });

app/views/products/add_variant.js.erb
$('#variants').prepend("<%= j(render partial: 'add_variant')%>");

app/views/products/index.html.haml
%div.container
  %div.row
    %div.card
      = render partial: 'products'

app/views/products/show.html.haml
%div.container
  %div.row
    %div.card
      %div.row
        %div.col-4.p-2
          %h5= t('common_texts.order#')
          %h5 :
          %h5= @product['order_id']

        %div.col-4.p-2
          %h5= t('common_texts.name')
          %h5 :
          %h5= @product['name']
         
        %div.col-4.p-2
          %h5= t('common_texts.description')
          %h5 :
          %h5= @product['description']
        
        %div.col-4.p-2
          %h5= t('common_texts.date_create')
          %h5 :
          %h5= DateTime.parse(@product['created_at']).strftime('%Y-%m-%d %H:%M')

        %div.col-12.p-2
          %div
            %h2= t('common_texts.variants')
          %div.col-12
            - @product['variants'].each do |variant|
              %div.variants
                %div.col-6.p-2
                  %h5= t('common_texts.name')
                  %h5 :
                  %h5= variant['name']
    
                %div.col-6.p-2
                  %h5= t('common_texts.price')
                  %h5 :
                  %h5= number_to_currency(variant['price'])
        
        %div.links.col-10.pt-4
          %a.btn.btn-link{href: "/products"}= t('sales.inputs.back')